### ISSUE TITLE
Adding a new python library in docker environment

### ISSUE THREAD

**Issue by velociraptor111** [aws/sagemaker-mxnet-serving-container#73]
How do I add a new python library to be used in my image environment, such that  *input_fn* , *output_fn* , etc.. in my entry point file could use it? 

Do I simply add it in the **Dockerfile.cpu** here ??
```
RUN ${PIP} install --no-cache-dir mxnet-mkl==$MX_VERSION \
                                  mxnet-model-server==$MMS_VERSION \
                                  keras-mxnet==2.2.4.1 \
                                  numpy==1.14.5 \
                                  onnx==1.4.1 \
                                  NEWLIBRARY1\
                                  NEWLIBRARY2
```

**Comment by laurenyu** [comment]
sorry for the slow response here!

if you want to build your own image, yes, you can add those libraries to the Dockerfile there. we're also in progress of adding requirements.txt support, which is being tracked here: https://github.com/aws/sagemaker-inference-toolkit/issues/9. It's currently code-complete but awaiting release in our pre-built Docker images.
