### ISSUE TITLE
Does sagemaker mxnet serving container by default not handle parallel requests?

### ISSUE THREAD

**Issue by velociraptor111** [aws/sagemaker-mxnet-serving-container#79]
I initially thought that this applies to all containers, but after playing around with sagemaker tensorflow serving container, I noticed that tensorflow serving container was able to handle concurrent requests at the same time. 

I am now wondering if this is only a sagemaker mxnet serving container issue not being able to serve concurrent requests at the same time?

Here is a reference to my full question: https://github.com/awslabs/amazon-sagemaker-examples/issues/923 

Here is the same question I asked in aws forum: https://forums.aws.amazon.com/thread.jspa?threadID=312775&tstart=0

## Edit

For more information , this is what my entry_point file looks like in my experiment with sagemaker mxnet serving container.

```python
import logging, requests, os, io, glob, time
from datetime import datetime
import json
def model_fn(model_dir):
    return None
def transform_fn(model, request_body, content_type, accept_type):
    print("Inside transform function !")        
    request_body_dict = json.loads(request_body)    
    video_id = request_body_dict["video_id"]
    print("VIDEO  ID: ", video_id)
    print("Sleeping now .. ")
    time.sleep(5)
    print("Done. Returning ...")
    return json.dumps({"Status": "Done"})
```

I have a synonymous script for Tensorflow container where it just sleeps for 5 seconds and then returns.

**Comment by velociraptor111** [comment]
Hi @laurenyu any comments ?

**Comment by laurenyu** [comment]
I'm not too sure, unfortunately, but I've reached out to a related team to see if they have any insight. Thanks for your patience!

**Comment by velociraptor111** [comment]
Thank you! Looking forward to it.

**Comment by velociraptor111** [comment]
Hi @laurenyu, any updates? Thanks in advance

**Comment by velociraptor111** [comment]
Hi @laurenyu, any updates? 
Is there a link where I can reference to the question?

**Comment by pinal-patel** [comment]
Hi @laurenyu 
Same issue on PyTorch container any update on this ?

**Comment by alexgl-github** [comment]
Multi model server (MMS) can handle concurrent inference requests for any supported framework including MxNet. 

Number of concurrent requests is configured by config.properties parameter 
default_workers_per_model=<value>
where <value> will be the number of simultaneous inference requests.
If not set it will default to number of cpu cores in the system.

**Comment by velociraptor111** [comment]
Thanks for replying! I have yet to try it out, but is there anyway I can supply this parameter through the sagemaker client call when creating/deploying the model ? 

The other way I can think about is to build a new docker image with this parameter set and upload to ECR and use that image instead of the default.

**Comment by laurenyu** [comment]
@velociraptor111 `MXNetModel` has [a parameter called `model_server_workers`](https://sagemaker.readthedocs.io/en/stable/sagemaker.mxnet.html#sagemaker.mxnet.model.MXNetModel) that [should get passed through](https://github.com/aws/sagemaker-inference-toolkit/blob/master/src/sagemaker_inference/model_server.py#L127)

(and [same with PyTorch](https://sagemaker.readthedocs.io/en/stable/sagemaker.pytorch.html#sagemaker.pytorch.model.PyTorchModel) @pinal-patel)

**Comment by velociraptor111** [comment]
Thank you both for the clarification.
