### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'nginx': 'nginx'

### ISSUE THREAD

**Issue by AaronSpieler** [aws/sagemaker-mxnet-serving-container#80]
Hello,

So I get this error:

`FileNotFoundError: [Errno 2] No such file or directory: 'nginx': 'nginx'`

With traceback:

```
Traceback (most recent call last):
  File "/usr/local/bin/serve", line 11, in <module>
    load_entry_point('sagemaker-containers==2.4.10.post0', 'console_scripts', 'serve')()
  File "/usr/local/lib/python3.6/site-packages/sagemaker_containers/cli/serve.py", line 17, in main
    server.start(env.ServingEnv().framework_module)
  File "/usr/local/lib/python3.6/site-packages/sagemaker_containers/_server.py", line 74, in start
    nginx = subprocess.Popen(['nginx', '-c', nginx_config_file])
  File "/usr/local/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
```

When calling `.deploy()` on GluonTSFramework (basically the same as MXNetFramework) using a slightly modified version of the provided docker images.
The Error and Traceback is copied from CloudWatch.

I have also tried to install nginx in the docker image, but it didnt  fix the problem.

GluonTSFramwork pull request: 
https://github.com/awslabs/gluon-ts/pull/444/ 

All files:
https://github.com/awslabs/gluon-ts/tree/c15d0c498417caa68c3abde29bc9b2ae405a142c/src/gluonts/nursery/sagemaker_sdk

The slightly modified docker file: 
https://github.com/awslabs/gluon-ts/tree/c15d0c498417caa68c3abde29bc9b2ae405a142c/src/gluonts/nursery/sagemaker_sdk/docker_images/cpu_serving

Do you know how to fix this issue? I suspect the container is somehow

**Comment by laurenyu** [comment]
@AaronSpieler how did you build `sagemaker_mxnet_serving_container.tar.gz`?

The error and stacktrace look like you're using code from sagemaker-mxnet-container <= 2.0.0 rather than the code in this repository.

**Comment by AaronSpieler** [comment]
I do it it in the Makefile:

```
git clone https://github.com/aws/sagemaker-mxnet-serving-container.git
cd sagemaker-mxnet-serving-container; python setup.py sdist
cp sagemaker-mxnet-serving-container/dist/sagemaker_mxnet_serving_container-*.tar.gz sagemaker_mxnet_serving_container.tar.gz
cp sagemaker-mxnet-serving-container/docker/1.4.1/py3/config.properties .
cp sagemaker-mxnet-serving-container/docker/1.4.1/py3/mms-entrypoint.py .```

So this should be the newest version on the master branch...

**Comment by laurenyu** [comment]
I don't immediately see anything in your code that would point to the old serving stack (i.e. sagemaker-containers) - just as a sanity check, if you look at your model/endpoint config/endpoint in the AWS console, does it point to the ECR image you're expecting?

**Comment by AaronSpieler** [comment]
Ok, so you were correct, due to a bug in my implementation, the training image was used instead of the specified serving image. THX!
