### ISSUE TITLE
HandlerService error message can be improved

### ISSUE THREAD

**Issue by leezu** [aws/sagemaker-mxnet-serving-container#95]
https://github.com/aws/sagemaker-mxnet-serving-container/blob/a325d98ab4eb72912fc5b18434eb048053cf794a/src/sagemaker_mxnet_serving_container/handler_service.py#L43-L57

raises `Unsupported model type: {}` if user didn't implement `model_fn` and doesn't return a Module or Block.

It would be good to add a sentence: "Did you forget to implement `model_fn`?"

**Comment by laurenyu** [comment]
sorry for the lack of response here, and thanks for submitting a PR!
